### ISSUE TITLE
YU Connect club registration

### ISSUE THREAD

**Issue by unforgettableid** [SSADC-at-york/yorku-dev#13]
I think it'd be good if SSADC became an officially-registered club with YU Connect / SCLD.

## Benefits

This would allow us and/or our work to become more discoverable:

* We would get a club listing on the YU Connect website.
* We could do tabling during club fair.  This happens at least once a year.
* We could do [tabling in Central Square](https://www.yorku.ca/scld/student-engagement/club-policies-and-guidelines/use-of-space/) during random days.

When tabling, maybe we could bring a laptop and a monitor.  We could show an infinitely-looping video demonstrating the cool things we've made.  Video can help to attract eyeballs and new users.  Hopefully the monitor will work well at the club fair, even if there's direct sunlight.  Maybe we could also [borrow](https://yorku.campuslabs.ca/engage/submitter/form/start/17276) a monitor and/or a projector from the school.

Being registered might also let club members to have their membership status listed on their [Co-Curricular record](https://www.yorku.ca/scld/student-engagement/join-register-or-create-an-organization/#:~:text=identify%20appropriate%20affiliations.-,Co%2DCurricular%20Record,and%20the%20organizations%20that%20you%20have%20joined%20while%20at%20your%20institution.,-Note%3A%20We).

We can get registered with SCLD by filling in [this form](https://yorku.campuslabs.ca/engage/register).

### Timing

New club registration is only possible every year between May and September.  [(Source.)](https://www.yorku.ca/scld/student-engagement/join-register-or-create-an-organization/#:~:text=Note%3A%20This%20option%20is%20open%20every%20year%20from%20May%20%2D%20September.)

## Conclusion

What are your thoughts?

**Comment by JudahGoldstein** [comment]
We don't meet the qualifications, we are incorporating under CSHUB.

**Comment by unforgettableid** [comment]
PresidentKevvol [wrote](https://github.com/mahfoozm/YorkURMP/issues/13#issuecomment-2144034036):  "We are a sub-club under CSHub, but with more autonomy than a usual 'department' within a club. In a way, like Canada and Britain. Many of our members are in both groups. So, technically, their office is also our office, if we should ever need to use one."

Judah [added](https://github.com/mahfoozm/YorkURMP/issues/13#issuecomment-2144034260):  "We ... are under the CSHub umbrella, we aren't large enough for club registration, and the nature of our mission means our membership is highly variable."
