### ISSUE TITLE
Lassonde club registration

### ISSUE THREAD

**Issue by unforgettableid** [SSADC-at-york/yorku-dev#14]
If SSADC gets registered with YU Connect / SCLD, we can optionally register with Lassonde next.

## Benefits

The Lassonde website writes that the benefits of Lassonde club registration are:

*  Club funding.
*  Room booking privileges in the Bergeron building.
*  Bergeron project and storage space, if available.  [(Source.)](https://lassonde.yorku.ca/student-life/lassonde-club-registration-starting-a-new-club)

## Steps

*  [Registering](https://github.com/SSADC-at-york/yorku-dev/issues/13) with YU Connect / SCLD.
*  Finding a faculty advisor.
*  Getting Lassonde club approval.  [Kayla Lascasas](https://atlas.cafe.uit.yorku.ca/atlas/servlet/atlas/action/AtlasAction/template/person.vm?eventsubmit_doperson=Person&searchp=143694) might be able to grant this.
*  There are more steps listed [here](https://lassonde.yorku.ca/student-life/lassonde-club-registration-starting-a-new-club).

## Conclusion

What are your thoughts?

**Comment by JudahGoldstein** [comment]
We don't meet the qualifications, we are incorporating under CSHUB.

**Comment by unforgettableid** [comment]
PresidentKevvol [wrote](https://github.com/mahfoozm/YorkURMP/issues/13#issuecomment-2144034036):  "We are a sub-club under CSHub, but with more autonomy than a usual 'department' within a club. In a way, like Canada and Britain. Many of our members are in both groups. So, technically, their office is also our office, if we should ever need to use one."

Judah [added](https://github.com/mahfoozm/YorkURMP/issues/13#issuecomment-2144034260):  "We ... are under the CSHub umbrella, we aren't large enough for club registration, and the nature of our mission means our membership is highly variable."
