### ISSUE TITLE
YFS club registration

### ISSUE THREAD

**Issue by unforgettableid** [SSADC-at-york/yorku-dev#15]
I think it'd be good if SSADC became an officially-registered club with YFS.

## Benefits

Benefits may include:

*  Free graphic design:  a logo, poster, flyer, banner, business card, and maybe more.
*  One free vinyl banner per year.
*  $125 of free photocopying and poster printing per year.
*  100 free club business cards per year.
*  Possible funding.  Maybe up to $300 of base funding per year. Plus, possibly up to $800 if we want to run an event (e.g. a hackathon).
*  Borrowing some items from YFS for free, including event tents, water coolers, and game consoles.  (It's fun to have game consoles handy during a hackathon.)
*  [Other free help](https://www.yfs.ca/clubservices#:~:text=GENERAL%20HELP,accommodate%20your%20needs.).

More information on these possible benefits is [here](https://www.yfs.ca/clubservices).

## The form

Registering a club with YFS requires filling in [an online form](https://www.yfs.ca/forms).

## Conclusion

What are your thoughts?

**Comment by JudahGoldstein** [comment]
We don't meet the qualifications, we are incorporating under CSHUB.

**Comment by unforgettableid** [comment]
PresidentKevvol [wrote](https://github.com/mahfoozm/YorkURMP/issues/13#issuecomment-2144034036):  "We are a sub-club under CSHub, but with more autonomy than a usual 'department' within a club. In a way, like Canada and Britain. Many of our members are in both groups. So, technically, their office is also our office, if we should ever need to use one."

Judah [added](https://github.com/mahfoozm/YorkURMP/issues/13#issuecomment-2144034260):  "We ... are under the CSHub umbrella, we aren't large enough for club registration, and the nature of our mission means our membership is highly variable."
