### ISSUE TITLE
Please include a link to the YorkURMP extension on the yorku.dev homepage

### ISSUE THREAD

**Issue by unforgettableid** [SSADC-at-york/yorku-dev#5]
Many people don't know about the [YorkURMP](https://www.reddit.com/r/yorku/comments/102qjeo/made_a_ratemyprofessors_extension_for_the_york/) extension for Chrome and Firefox.  It modifies the York Courses website to include Rate My Professors ratings for many (but not all) professors.

It would be good if you could please add a link from the https://yorku.dev/#projects page to [the relevant Chrome Web Store page](https://chrome.google.com/webstore/detail/yorkurmp/cdhfogbjpedkpmapnddalehbjdjahfmp).  Firefox users, I guess, would then be on their own.

This was discussed [elsewhere](https://www.reddit.com/r/yorku/comments/102qjeo/made_a_ratemyprofessors_extension_for_the_york/j2yav6q/), six months ago, but nothing ever came of it.

I thank you all, for all the valuable volunteer work that you do for your fellow students!

Cc:  @mahfoozm.

**Comment by mahfoozm** [comment]
![image](https://github.com/SSADC-at-york/yorku-dev/assets/95328615/e4096838-c8d6-4de7-8dd4-5f059fd1e628)

**Comment by unforgettableid** [comment]
Appreciated!
